### ISSUE TITLE
Reactor Choice

### ISSUE THREAD

**Issue by samgdotson** [arfc/cairo#23]
This issue can be closed when @samgdotson and @katyhuff have discussed which kind of reactor to model.

1. The choice of reactor determines the ideal prediction window (e.g. Does the reactor need 3 hours or 3 days of notice?). 
2. The reactor will need a full-core model from SERPENT to obtain kinetics parameters (e.g. beta, lambda)
3. Using kinetics parameters, a point kinetics model using ``PyRK`` will be used to identify reactor transient behavior.

**Comment by katyhuff** [comment]
@samgdotson -- I don't entirely remember what this was about. Was this handled already, is this still active, should we close without fixing, or leave it to some future person?

**Comment by samgdotson** [comment]
This would have been for a different PhD / master's project. I think this is a "won't fix."
