### ISSUE TITLE
Code examples for sunrise.py

### ISSUE THREAD

**Issue by samgdotson** [arfc/cairo#32]
Currently, there is an example code in ``sunrise.py`` under
```python
if __name__ == "__main__":
 # code
```
The example was helpful for debugging the initial script but really shouldn't live there long term. It will also be helpful for future users if there are some examples provided.
This issue can be closed when
- [ ] a folder named ``examples`` has been added
- [ ] some/an examples for using the code to generate data and plots have been added

The basic examples already exist in ``sunrise.py``, but should be given more explanation. 
For inspiration, use [matplotlib](https://matplotlib.org/tutorials/introductory/pyplot.html)'s tutorial.

**Comment by nsryan2** [comment]
@samgdotson Do you think it would be a good idea to do these examples in jupyter notebooks? If you eventually want to build documentation with Sphinx they could be displayed there.

**Comment by samgdotson** [comment]
@nsryan2 It's generally better practice to have examples built-in to the documentation. You can do this by adding examples the docstrings directly. Which is essentially what MPL does. It's probably a good idea to combine this issue with #33 (sphinx docs). I have a sphinx branch started as well, to help you get going. 

Here's some guidance:
* https://www.sphinx-doc.org/en/1.5/markup/code.html
* https://pythonhosted.org/an_example_pypi_project/sphinx.html#full-code-example
